services:

  postgres:
    image: postgres:16
    container_name: ${SQL_CONTAINTER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    ports:
      - "${SQL_PORT}:${SQL_PORT_EXPOSE}"
    volumes:
      - ./app/SQL/data:/var/lib/postgresql/data
      - ./app/SQL/setup.postgre.sql:/docker-entrypoint-initdb.d/setup.postgre.sql

  appIndex:
    build:
      context: .
      dockerfile: Dockerfile
      target: Index
    image: webapp/index:1.0
    ports:
      - "${APP_INDEX_PORT}-${APP_INDEX_PORT + APP_INDEX_PORT_LEN - 1}:${API_INDEX_PORT_EXPOSE}-${API_INDEX_PORT_EXPOSE + APP_INDEX_PORT_LEN - 1}"

  appGame:
    build:
      context: .
      dockerfile: Dockerfile
      target: Game
    image: webapp/game:1.0
    ports:
      - "${APP_GAME_PORT}-${APP_GAME_PORT + APP_GAME_PORT_LEN - 1}:${API_GAME_PORT_EXPOSE}-${API_GAME_PORT_EXPOSE + APP_GAME_PORT_LEN - 1}"

  apiStyleSheet:
    build:
      context: .
      dockerfile: Dockerfile
      target: StyleSheet
    image: webapp/stylesheet:1.0
    ports:
      - "${APP_STYLESHEET_PORT}-${APP_STYLESHEET_PORT + APP_STYLESHEET_PORT_LEN - 1}:${API_STYLESHEET_PORT_EXPOSE}-${API_STYLESHEET_PORT_EXPOSE + APP_STYLESHEET_PORT_LEN - 1}"